// Code generated by ent, DO NOT EDIT.

package fileentity

const (
	// Label holds the string label denoting the fileentity type in the database.
	Label = "file_entity"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the fileentity in the database.
	Table = "file_entities"
)

// Columns holds all SQL columns for fileentity fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
