// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"uploader/ent/fileentity"
	"uploader/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FileEntityUpdate is the builder for updating FileEntity entities.
type FileEntityUpdate struct {
	config
	hooks    []Hook
	mutation *FileEntityMutation
}

// Where appends a list predicates to the FileEntityUpdate builder.
func (feu *FileEntityUpdate) Where(ps ...predicate.FileEntity) *FileEntityUpdate {
	feu.mutation.Where(ps...)
	return feu
}

// Mutation returns the FileEntityMutation object of the builder.
func (feu *FileEntityUpdate) Mutation() *FileEntityMutation {
	return feu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (feu *FileEntityUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(feu.hooks) == 0 {
		affected, err = feu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FileEntityMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			feu.mutation = mutation
			affected, err = feu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(feu.hooks) - 1; i >= 0; i-- {
			if feu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = feu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, feu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (feu *FileEntityUpdate) SaveX(ctx context.Context) int {
	affected, err := feu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (feu *FileEntityUpdate) Exec(ctx context.Context) error {
	_, err := feu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (feu *FileEntityUpdate) ExecX(ctx context.Context) {
	if err := feu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (feu *FileEntityUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   fileentity.Table,
			Columns: fileentity.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: fileentity.FieldID,
			},
		},
	}
	if ps := feu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, feu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fileentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// FileEntityUpdateOne is the builder for updating a single FileEntity entity.
type FileEntityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FileEntityMutation
}

// Mutation returns the FileEntityMutation object of the builder.
func (feuo *FileEntityUpdateOne) Mutation() *FileEntityMutation {
	return feuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (feuo *FileEntityUpdateOne) Select(field string, fields ...string) *FileEntityUpdateOne {
	feuo.fields = append([]string{field}, fields...)
	return feuo
}

// Save executes the query and returns the updated FileEntity entity.
func (feuo *FileEntityUpdateOne) Save(ctx context.Context) (*FileEntity, error) {
	var (
		err  error
		node *FileEntity
	)
	if len(feuo.hooks) == 0 {
		node, err = feuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FileEntityMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			feuo.mutation = mutation
			node, err = feuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(feuo.hooks) - 1; i >= 0; i-- {
			if feuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = feuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, feuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*FileEntity)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from FileEntityMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (feuo *FileEntityUpdateOne) SaveX(ctx context.Context) *FileEntity {
	node, err := feuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (feuo *FileEntityUpdateOne) Exec(ctx context.Context) error {
	_, err := feuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (feuo *FileEntityUpdateOne) ExecX(ctx context.Context) {
	if err := feuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (feuo *FileEntityUpdateOne) sqlSave(ctx context.Context) (_node *FileEntity, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   fileentity.Table,
			Columns: fileentity.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: fileentity.FieldID,
			},
		},
	}
	id, ok := feuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FileEntity.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := feuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fileentity.FieldID)
		for _, f := range fields {
			if !fileentity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != fileentity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := feuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &FileEntity{config: feuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, feuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fileentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
