// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"uploader/ent/fileentity"
	"uploader/ent/user"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FileEntityCreate is the builder for creating a FileEntity entity.
type FileEntityCreate struct {
	config
	mutation *FileEntityMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (fec *FileEntityCreate) SetName(s string) *FileEntityCreate {
	fec.mutation.SetName(s)
	return fec
}

// SetType sets the "type" field.
func (fec *FileEntityCreate) SetType(s string) *FileEntityCreate {
	fec.mutation.SetType(s)
	return fec
}

// SetSize sets the "size" field.
func (fec *FileEntityCreate) SetSize(i int64) *FileEntityCreate {
	fec.mutation.SetSize(i)
	return fec
}

// SetURL sets the "url" field.
func (fec *FileEntityCreate) SetURL(s string) *FileEntityCreate {
	fec.mutation.SetURL(s)
	return fec
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (fec *FileEntityCreate) SetOwnerID(id int) *FileEntityCreate {
	fec.mutation.SetOwnerID(id)
	return fec
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (fec *FileEntityCreate) SetNillableOwnerID(id *int) *FileEntityCreate {
	if id != nil {
		fec = fec.SetOwnerID(*id)
	}
	return fec
}

// SetOwner sets the "owner" edge to the User entity.
func (fec *FileEntityCreate) SetOwner(u *User) *FileEntityCreate {
	return fec.SetOwnerID(u.ID)
}

// Mutation returns the FileEntityMutation object of the builder.
func (fec *FileEntityCreate) Mutation() *FileEntityMutation {
	return fec.mutation
}

// Save creates the FileEntity in the database.
func (fec *FileEntityCreate) Save(ctx context.Context) (*FileEntity, error) {
	var (
		err  error
		node *FileEntity
	)
	if len(fec.hooks) == 0 {
		if err = fec.check(); err != nil {
			return nil, err
		}
		node, err = fec.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FileEntityMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = fec.check(); err != nil {
				return nil, err
			}
			fec.mutation = mutation
			if node, err = fec.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(fec.hooks) - 1; i >= 0; i-- {
			if fec.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = fec.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, fec.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*FileEntity)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from FileEntityMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (fec *FileEntityCreate) SaveX(ctx context.Context) *FileEntity {
	v, err := fec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fec *FileEntityCreate) Exec(ctx context.Context) error {
	_, err := fec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fec *FileEntityCreate) ExecX(ctx context.Context) {
	if err := fec.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fec *FileEntityCreate) check() error {
	if _, ok := fec.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "FileEntity.name"`)}
	}
	if v, ok := fec.mutation.Name(); ok {
		if err := fileentity.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "FileEntity.name": %w`, err)}
		}
	}
	if _, ok := fec.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "FileEntity.type"`)}
	}
	if _, ok := fec.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "FileEntity.size"`)}
	}
	if _, ok := fec.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "FileEntity.url"`)}
	}
	return nil
}

func (fec *FileEntityCreate) sqlSave(ctx context.Context) (*FileEntity, error) {
	_node, _spec := fec.createSpec()
	if err := sqlgraph.CreateNode(ctx, fec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (fec *FileEntityCreate) createSpec() (*FileEntity, *sqlgraph.CreateSpec) {
	var (
		_node = &FileEntity{config: fec.config}
		_spec = &sqlgraph.CreateSpec{
			Table: fileentity.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: fileentity.FieldID,
			},
		}
	)
	if value, ok := fec.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: fileentity.FieldName,
		})
		_node.Name = value
	}
	if value, ok := fec.mutation.GetType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: fileentity.FieldType,
		})
		_node.Type = value
	}
	if value, ok := fec.mutation.Size(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: fileentity.FieldSize,
		})
		_node.Size = value
	}
	if value, ok := fec.mutation.URL(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: fileentity.FieldURL,
		})
		_node.URL = value
	}
	if nodes := fec.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fileentity.OwnerTable,
			Columns: []string{fileentity.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_files = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FileEntityCreateBulk is the builder for creating many FileEntity entities in bulk.
type FileEntityCreateBulk struct {
	config
	builders []*FileEntityCreate
}

// Save creates the FileEntity entities in the database.
func (fecb *FileEntityCreateBulk) Save(ctx context.Context) ([]*FileEntity, error) {
	specs := make([]*sqlgraph.CreateSpec, len(fecb.builders))
	nodes := make([]*FileEntity, len(fecb.builders))
	mutators := make([]Mutator, len(fecb.builders))
	for i := range fecb.builders {
		func(i int, root context.Context) {
			builder := fecb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FileEntityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (fecb *FileEntityCreateBulk) SaveX(ctx context.Context) []*FileEntity {
	v, err := fecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fecb *FileEntityCreateBulk) Exec(ctx context.Context) error {
	_, err := fecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fecb *FileEntityCreateBulk) ExecX(ctx context.Context) {
	if err := fecb.Exec(ctx); err != nil {
		panic(err)
	}
}
