// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"uploader/ent/fileentity"
	"uploader/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FileEntityDelete is the builder for deleting a FileEntity entity.
type FileEntityDelete struct {
	config
	hooks    []Hook
	mutation *FileEntityMutation
}

// Where appends a list predicates to the FileEntityDelete builder.
func (fed *FileEntityDelete) Where(ps ...predicate.FileEntity) *FileEntityDelete {
	fed.mutation.Where(ps...)
	return fed
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (fed *FileEntityDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(fed.hooks) == 0 {
		affected, err = fed.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FileEntityMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			fed.mutation = mutation
			affected, err = fed.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(fed.hooks) - 1; i >= 0; i-- {
			if fed.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = fed.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, fed.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (fed *FileEntityDelete) ExecX(ctx context.Context) int {
	n, err := fed.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (fed *FileEntityDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: fileentity.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: fileentity.FieldID,
			},
		},
	}
	if ps := fed.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, fed.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// FileEntityDeleteOne is the builder for deleting a single FileEntity entity.
type FileEntityDeleteOne struct {
	fed *FileEntityDelete
}

// Exec executes the deletion query.
func (fedo *FileEntityDeleteOne) Exec(ctx context.Context) error {
	n, err := fedo.fed.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{fileentity.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (fedo *FileEntityDeleteOne) ExecX(ctx context.Context) {
	fedo.fed.ExecX(ctx)
}
