// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// FileEntity is the predicate function for fileentity builders.
type FileEntity func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
